### ISSUE TITLE
docker-compose not working

### ISSUE THREAD

**Issue by changchichung** [wiretrustee/wiretrustee#105]
barely change in docker-compose and turnserver.conf

just clone the repo and run docker-compose but return errors
```
2021-09-01 10:09:55 [changch@hqdc034 infrastructure_files]$ docker-compose up -d
Creating network "infrastructure_files_default" with the default driver
Pulling signal (wiretrustee/signal:latest)...
latest: Pulling from wiretrustee/signal
0d7d70899875: Already exists
f7eef7515175: Pull complete
a821ee61e63e: Pull complete
bb1f9feb32be: Pull complete
Digest: sha256:95ef500c6d216d4d884405d434e3188b19320fc3f777e8fcfc1d8b0befd80879
Status: Downloaded newer image for wiretrustee/signal:latest
Pulling management (wiretrustee/management:latest)...
latest: Pulling from wiretrustee/management
ERROR: no matching manifest for linux/amd64 in the manifest list entries
2021-09-01 10:10:11 [changch@hqdc034 infrastructure_files]$ ls
config.json  docker-compose.yml  turnserver.conf
2021-09-01 10:10:21 [changch@hqdc034 infrastructure_files]$
```
any suggestions ??

**Comment by mlsmaycon** [comment]
Hello @changchichung this is caused because of a bug released in the Release candidate, #104 fixes the issue but will be applied only on the next RC.

In the mean time, can you use the tag 0.1.0-rc-1 for management?

**Comment by changchichung** [comment]
#### tag 0.1.0-rc-1

docker-compose.yml
```
version: "3"
services:
  # Signal
  signal:
    image: wiretrustee/signal:0.1.0-rc-1-amd64
    restart: unless-stopped
    volumes:
      - wiretrustee-mgmt:/var/lib/wiretrustee
    ports:
      - 10000:10000
#     # port and command for Let's Encrypt validation
#      - 443:443
#    command: ["--letsencrypt-domain", "<YOUR-DOMAIN>"]
  # Management
  management:
    image: wiretrustee/management:0.1.0-rc-1-amd64
    restart: unless-stopped
    volumes:
      - wiretrustee-mgmt:/var/lib/wiretrustee
      - ./config.json:/etc/wiretrustee/config.json
    ports:
      - 33073:33073
#     # port and command for Let's Encrypt validation
#      - 443:443
#    command: ["--letsencrypt-domain", "<YOUR-DOMAIN>"]
  # Coturn
  coturn:
    image: coturn/coturn
    restart: unless-stopped
    domainname: stun.wiretrustee.com
    volumes:
      - ./turnserver.conf:/etc/turnserver.conf:ro
#      - ./privkey.pem:/etc/coturn/private/privkey.pem:ro
#      - ./cert.pem:/etc/coturn/certs/cert.pem:ro
    network_mode: host
volumes:
  wiretrustee-mgmt:
  wiretrustee-signal:
```
docker-compose up 
```
2021-09-02 08:19:11 [changch@hqdc034 infrastructure_files]$ docker-compose up -d
Pulling signal (wiretrustee/signal:0.1.0-rc-1-amd64)...
0.1.0-rc-1-amd64: Pulling from wiretrustee/signal
Digest: sha256:fbdfa8a6fd64d7e108130eb0a894f0307ae6d835d4edf70db029f206bcd007a6
Status: Downloaded newer image for wiretrustee/signal:0.1.0-rc-1-amd64
Pulling management (wiretrustee/management:0.1.0-rc-1-amd64)...
0.1.0-rc-1-amd64: Pulling from wiretrustee/management
5f8c69dfd0d4: Pull complete
058300e50e8e: Pull complete
f39f4b92c7d9: Pull complete
Digest: sha256:762dcac4be80d1efad7fa48be04656d3e3e7b3b8b95df8ceb43c5012a74e7f8a
Status: Downloaded newer image for wiretrustee/management:0.1.0-rc-1-amd64
Recreating infrastructure_files_signal_1   ... done
Recreating infrastructure_files_coturn_1   ... done
Creating infrastructure_files_management_1 ... done
```

but the management container is not in healthy state
```
0f2fb827e798   coturn/coturn                             "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes                                                                                              infrastructure_files_coturn_1
320ebdc5d297   wiretrustee/signal:0.1.0-rc-1-amd64       "/go/bin/wiretrustee…"   2 minutes ago   Up 2 minutes                    0.0.0.0:10000->10000/tcp, :::10000->10000/tcp                             infrastructure_files_signal_1
a40a95f1dde1   wiretrustee/management:0.1.0-rc-1-amd64   "/go/bin/wiretrustee…"   2 minutes ago   Restarting (1) 46 seconds ago                                                                             infrastructure_files_management_1
```

and docker logs shows missing something
```
2021-09-02 08:22:05 [changch@hqdc034 infrastructure_files]$ docker logs -f infrastructure_files_management_1
time="2021-09-02T00:19:30Z" level=fatal msg="failed reading provided config file: /etc/wiretrustee/management.json: open /etc/wiretrustee/management.json: no such file or directory"
time="2021-09-02T00:19:31Z" level=fatal msg="failed reading provided config file: /etc/wiretrustee/management.json: open /etc/wiretrustee/management.json: no such file or directory"
time="2021-09-02T00:19:32Z" level=fatal msg="failed reading provided config file: /etc/wiretrustee/management.json: open /etc/wiretrustee/management.json: no such file or directory"
time="2021-09-02T00:19:32Z" level=fatal msg="failed reading provided config file: /etc/wiretrustee/management.json: open /etc/wiretrustee/management.json: no such file or directory"
time="2021-09-02T00:19:34Z" level=fatal msg="failed reading provided config file: /etc/wiretrustee/management.json: open /etc/wiretrustee/management.json: no such file or directory"
time="2021-09-02T00:19:36Z" level=fatal msg="failed reading provided config file: /etc/wiretrustee/management.json: open /etc/wiretrustee/management.json: no such file or directory"
time="2021-09-02T00:19:40Z" level=fatal msg="failed reading provided config file: /etc/wiretrustee/management.json: open /etc/wiretrustee/management.json: no such file or directory"
time="2021-09-02T00:19:47Z" level=fatal msg="failed reading provided config file: /etc/wiretrustee/management.json: open /etc/wiretrustee/management.json: no such file or directory"
time="2021-09-02T00:20:00Z" level=fatal msg="failed reading provided config file: /etc/wiretrustee/management.json: open /etc/wiretrustee/management.json: no such file or directory"
time="2021-09-02T00:20:26Z" level=fatal msg="failed reading provided config file: /etc/wiretrustee/management.json: open /etc/wiretrustee/management.json: no such file or directory"
time="2021-09-02T00:21:18Z" level=fatal msg="failed reading provided config file: /etc/wiretrustee/management.json: open /etc/wiretrustee/management.json: no such file or directory"
time="2021-09-02T00:22:19Z" level=fatal msg="failed reading provided config file: /etc/wiretrustee/management.json: open /etc/wiretrustee/management.json: no such file or directory"
2021-09-02 08:22:29 [changch@hqdc034 infrastructure_files]$ 
```
